### ISSUE TITLE
要望

### ISSUE THREAD

**Issue by tm8r** [tm8r/MayaWindowSwitcher#4]
https://github.com/tm8r/MayaRecentFilesPlus/issues/2

**Comment by tm8r** [comment]
スクリプトエディタの問題以外は
v1.0.1にて対応済
https://github.com/tm8r/MayaWindowSwitcher/releases/tag/v1.0.1

**Comment by ezvfx** [comment]
ご対応ありがとうございました！
確認させていただきます。
